---
title: "Trabajo 1"
author: "XHV"
format:  
  html:
    toc: true
    embed-resources: true
---

## pkgs

```{r}
#| message: false
library(tidyverse)  # pkgs for data science
library(fpp3)    # pkgs for ts
library(plotly)  # plotly interactive plots
library(patchwork) # for handling many plots in one figure
library(tidyquant) # toolkit for financial analysis and downloading data
```

## ingresos por hospedaje

```{r}
aus_accommodation
```

```{r}
delete_cols <- c("CPI", "State")

tasmania <- aus_accommodation |>
  filter(State == "Tasmania") |>
  # select(-CPI, -State)
  # select(-c(CPI,State))
  # select(Date:Occupancy)  Con estas solo seleccionarias las que 
  # select(Date, State, Takings, Ocuupancy)     quieras
  select(-delete_cols) |>
  mutate(   # mutate para agregar o modificar columnas
    `Año bisiesto opción` = 1
  ) |>
  
  janitor::clean_names()  # clean_names todo en minusculas sin caracteres especiales

tasmania

tasmania |>
  glimpse()
names(tasmania)
#CTRL/CMD + SHIFT + M
```

```{r}
tasmania |>
  autoplot(takings, color = "slateblue1", size = 2)
```

We see that the Takings have an upward **trend**, yearly **seasonality**, and an increasing variance. We can try using a log transformation to stabilize the variance.

### Time plot

```{r}
p <- tasmania |>
  autoplot(log(takings), color = "slateblue1", size = 1) + 
  geom_point()

ggplotly(p, dynamicTicks = TRUE) |> 
  rangeslider()
```

### Season plot

```{r}
tasmania |>
  gg_season(log(takings))
```

### Subseries plot

```{r}
tasmania |>
  gg_subseries(log(takings))
```

En subseries la linea azul es el promedio a lo largo del tiempo

```{r}
tasmania |>
  gg_tsdisplay(takings, plot_type = "partial")
```

## Stocks data from Yahoo Finance

```{r}
stocks <- c("TSLA","GOOGL","MSFT","AAPL","CEMEXCPO.MX")

stocks_data <- tq_get(
  x = stocks,
  get = "stock.prices",
  from = "2014-01-01",
  to = today()-1
)

stocks_data
stocks_data |>
  distinct(symbol)

stocks_data <- stocks_data |>
  as_tsibble(index = date, key = symbol)

stocks_data
```

```{r}
stocks_data |> 
  ggplot(aes(x = date, y = close, color = symbol)) +
  theme_light() +
  geom_line()
```

```{r}
#| warning: false
stocks_data |> 
  filter(symbol == "AAPL") |> 
  ggplot(aes(x = date, open = open, high = high, low = low, close = close)) +
  theme_light() +
  geom_candlestick() +
  facet_wrap(~ symbol, ncol = 2, scales = "free_y")
```

